#!/usr/bin/env python3

"""
Usage: python3 tools/boss_teams.py

Phase 3b hand-authored boss fights for the endurance difficulty hack.

Holds curated teams for every boss (gym leaders, rivals, Wally, Magma/Aqua
admins+leaders, Elite Four, Champion, Steven) and splices them into
src/data/trainers.party, replacing each boss's AI line and mon blocks while
preserving the rest of its header (Name/Class/Pic/Music/Items/...).

Every boss mon: 31 IVs across the board, a set-appropriate nature, a held
item, an EV spread and a curated 4-move set. Constants (SPECIES_/ITEM_/
MOVE_/NATURE_/ABILITY_) are emitted directly so no display-name conversion
can drift.

Leader rematches (_2.._5) and Wally Victory Road rematches (VR_2..5) are
derived from the authored base team by flat level offsets, so Phase 4 can
scale from a consistent baseline. E4 teams here are the loop-0 versions.

Idempotent by construction: output depends only on this file's data, so
re-running produces byte-identical results.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PARTY_FILE = ROOT / "src/data/trainers.party"

AI_BOSS = "AI: Smart Trainer / Ace Pokemon / Hp Aware"
AI_TOP = "AI: Smart Trainer / Ace Pokemon / Hp Aware / Prediction"

IVS = "IVs: 31 HP / 31 Atk / 31 Def / 31 SpA / 31 SpD / 31 Spe"


def mon(species, level, item, nature, evs, moves, ability=None):
    return {
        "species": species,
        "level": level,
        "item": item,
        "nature": nature,
        "evs": evs,
        "moves": moves,
        "ability": ability,
    }


PHYS = "EVs: 252 Atk / 4 SpD / 252 Spe"
SPEC = "EVs: 252 SpA / 4 SpD / 252 Spe"
BULK_P = "EVs: 252 HP / 252 Atk / 4 Def"
BULK_S = "EVs: 252 HP / 252 SpA / 4 SpD"
WALL_D = "EVs: 252 HP / 252 Def / 4 SpD"
WALL_S = "EVs: 252 HP / 4 Def / 252 SpD"
MIXED_B = "EVs: 252 HP / 128 Def / 128 SpD"

# ---------------------------------------------------------------------------
# Gym leaders (story fights). Levels sit 3-5 above each gym's boosted
# trainers (Phase 3a): Rustboro 12, Dewford 16, Mauville 21, Lavaridge ~28,
# Petalburg 32, Fortree 36, Mossdeep 44, Sootopolis 48.
# ---------------------------------------------------------------------------

BOSSES = {}

BOSSES["TRAINER_ROXANNE_1"] = (AI_BOSS, [
    mon("SPECIES_GEODUDE", 14, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_STEALTH_ROCK", "MOVE_ROCK_TOMB", "MOVE_BULLDOZE", "MOVE_ROLLOUT"],
        "ABILITY_STURDY"),
    mon("SPECIES_ARON", 14, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_METAL_CLAW", "MOVE_ROCK_TOMB", "MOVE_HEADBUTT", "MOVE_PROTECT"],
        "ABILITY_STURDY"),
    mon("SPECIES_LILEEP", 15, "ITEM_ORAN_BERRY", "NATURE_CALM", WALL_S,
        ["MOVE_GIGA_DRAIN", "MOVE_ROCK_TOMB", "MOVE_CONFUSE_RAY", "MOVE_INGRAIN"]),
    mon("SPECIES_ANORITH", 15, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_ROCK_BLAST", "MOVE_FURY_CUTTER", "MOVE_METAL_CLAW", "MOVE_HARDEN"]),
    mon("SPECIES_LARVITAR", 16, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_ROCK_SLIDE", "MOVE_BITE", "MOVE_BULLDOZE", "MOVE_SCREECH"]),
    mon("SPECIES_NOSEPASS", 17, "ITEM_SITRUS_BERRY", "NATURE_BOLD", WALL_D,
        ["MOVE_ROCK_SLIDE", "MOVE_THUNDER_WAVE", "MOVE_SPARK", "MOVE_HARDEN"],
        "ABILITY_STURDY"),
])

BOSSES["TRAINER_BRAWLY_1"] = (AI_BOSS, [
    mon("SPECIES_MACHOP", 18, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_BULK_UP", "MOVE_KARATE_CHOP", "MOVE_ROCK_TOMB", "MOVE_KNOCK_OFF"],
        "ABILITY_GUTS"),
    mon("SPECIES_MEDITITE", 19, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_FAKE_OUT", "MOVE_FORCE_PALM", "MOVE_ZEN_HEADBUTT", "MOVE_BULLET_PUNCH"],
        "ABILITY_PURE_POWER"),
    mon("SPECIES_SHROOMISH", 19, "ITEM_ORAN_BERRY", "NATURE_BOLD", WALL_D,
        ["MOVE_STUN_SPORE", "MOVE_LEECH_SEED", "MOVE_MEGA_DRAIN", "MOVE_HEADBUTT"],
        "ABILITY_EFFECT_SPORE"),
    mon("SPECIES_TIMBURR", 20, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_MACH_PUNCH", "MOVE_LOW_KICK", "MOVE_ROCK_THROW", "MOVE_PAYBACK"],
        "ABILITY_GUTS"),
    mon("SPECIES_HERACROSS", 20, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_BRICK_BREAK", "MOVE_FURY_ATTACK", "MOVE_AERIAL_ACE", "MOVE_ENDURE"],
        "ABILITY_GUTS"),
    mon("SPECIES_MAKUHITA", 21, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_FAKE_OUT", "MOVE_KNOCK_OFF", "MOVE_VITAL_THROW", "MOVE_WHIRLWIND"],
        "ABILITY_THICK_FAT"),
])

BOSSES["TRAINER_WATTSON_1"] = (AI_BOSS, [
    mon("SPECIES_VOLTORB", 24, "ITEM_ORAN_BERRY", "NATURE_TIMID", SPEC,
        ["MOVE_THUNDER_WAVE", "MOVE_SPARK", "MOVE_SCREECH", "MOVE_SELF_DESTRUCT"],
        "ABILITY_STATIC"),
    mon("SPECIES_MAGNEMITE", 24, "ITEM_ORAN_BERRY", "NATURE_MODEST", BULK_S,
        ["MOVE_THUNDER_WAVE", "MOVE_SPARK", "MOVE_MIRROR_SHOT", "MOVE_SUPERSONIC"],
        "ABILITY_STURDY"),
    mon("SPECIES_ELECTRIKE", 25, "ITEM_ORAN_BERRY", "NATURE_TIMID", SPEC,
        ["MOVE_SHOCK_WAVE", "MOVE_QUICK_ATTACK", "MOVE_HOWL", "MOVE_BITE"],
        "ABILITY_LIGHTNING_ROD"),
    mon("SPECIES_LUXIO", 25, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_SPARK", "MOVE_BITE", "MOVE_ICE_FANG", "MOVE_ROAR"],
        "ABILITY_INTIMIDATE"),
    mon("SPECIES_PLUSLE", 25, "ITEM_ORAN_BERRY", "NATURE_TIMID", SPEC,
        ["MOVE_SHOCK_WAVE", "MOVE_FAKE_TEARS", "MOVE_ENCORE", "MOVE_QUICK_ATTACK"]),
    mon("SPECIES_MANECTRIC", 26, "ITEM_SITRUS_BERRY", "NATURE_TIMID", SPEC,
        ["MOVE_SHOCK_WAVE", "MOVE_BITE", "MOVE_QUICK_ATTACK", "MOVE_HOWL"],
        "ABILITY_STATIC"),
])

BOSSES["TRAINER_FLANNERY_1"] = (AI_BOSS, [
    mon("SPECIES_SLUGMA", 28, "ITEM_ORAN_BERRY", "NATURE_BOLD", BULK_S,
        ["MOVE_SUNNY_DAY", "MOVE_FLAME_BURST", "MOVE_ROCK_TOMB", "MOVE_YAWN"],
        "ABILITY_FLAME_BODY"),
    mon("SPECIES_NUMEL", 29, "ITEM_ORAN_BERRY", "NATURE_QUIET", BULK_S,
        ["MOVE_FLAME_BURST", "MOVE_BULLDOZE", "MOVE_AMNESIA", "MOVE_YAWN"]),
    mon("SPECIES_HOUNDOUR", 29, "ITEM_ORAN_BERRY", "NATURE_TIMID", SPEC,
        ["MOVE_FIRE_FANG", "MOVE_BITE", "MOVE_SOLAR_BEAM", "MOVE_ROAR"],
        "ABILITY_FLASH_FIRE"),
    mon("SPECIES_SOLROCK", 30, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_SUNNY_DAY", "MOVE_ROCK_SLIDE", "MOVE_PSYCHIC", "MOVE_HYPNOSIS"]),
    mon("SPECIES_CAMERUPT", 30, "ITEM_ORAN_BERRY", "NATURE_QUIET", BULK_S,
        ["MOVE_FLAME_BURST", "MOVE_BULLDOZE", "MOVE_ROCK_TOMB", "MOVE_AMNESIA"]),
    mon("SPECIES_TORKOAL", 31, "ITEM_WHITE_HERB", "NATURE_BOLD", WALL_D,
        ["MOVE_OVERHEAT", "MOVE_SOLAR_BEAM", "MOVE_BODY_SLAM", "MOVE_YAWN"],
        "ABILITY_WHITE_SMOKE"),
])

BOSSES["TRAINER_NORMAN_1"] = (AI_BOSS, [
    mon("SPECIES_SPINDA", 33, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_TEETER_DANCE", "MOVE_HYPNOSIS", "MOVE_DIZZY_PUNCH", "MOVE_SUCKER_PUNCH"],
        "ABILITY_OWN_TEMPO"),
    mon("SPECIES_DELCATTY", 34, "ITEM_SITRUS_BERRY", "NATURE_BOLD", WALL_D,
        ["MOVE_FAKE_OUT", "MOVE_SING", "MOVE_COVET", "MOVE_WISH"],
        "ABILITY_CUTE_CHARM"),
    mon("SPECIES_ZANGOOSE", 35, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_SWORDS_DANCE", "MOVE_SLASH", "MOVE_QUICK_ATTACK", "MOVE_SHADOW_CLAW"],
        "ABILITY_IMMUNITY"),
    mon("SPECIES_EXPLOUD", 35, "ITEM_ORAN_BERRY", "NATURE_MODEST", BULK_S,
        ["MOVE_HYPER_VOICE", "MOVE_FLAMETHROWER", "MOVE_SHADOW_BALL", "MOVE_HOWL"],
        "ABILITY_SOUNDPROOF"),
    mon("SPECIES_VIGOROTH", 36, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_BULK_UP", "MOVE_SLASH", "MOVE_ENCORE", "MOVE_FAINT_ATTACK"],
        "ABILITY_VITAL_SPIRIT"),
    mon("SPECIES_SLAKING", 37, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_BODY_SLAM", "MOVE_SHADOW_CLAW", "MOVE_BULLDOZE", "MOVE_SLACK_OFF"],
        "ABILITY_TRUANT"),
])

BOSSES["TRAINER_WINONA_1"] = (AI_BOSS, [
    mon("SPECIES_SWELLOW", 38, "ITEM_FLAME_ORB", "NATURE_JOLLY", PHYS,
        ["MOVE_FACADE", "MOVE_AERIAL_ACE", "MOVE_QUICK_ATTACK", "MOVE_U_TURN"],
        "ABILITY_GUTS"),
    mon("SPECIES_PELIPPER", 38, "ITEM_DAMP_ROCK", "NATURE_MODEST", BULK_S,
        ["MOVE_WATER_PULSE", "MOVE_AIR_CUTTER", "MOVE_PROTECT", "MOVE_ROOST"],
        "ABILITY_DRIZZLE"),
    mon("SPECIES_XATU", 39, "ITEM_ORAN_BERRY", "NATURE_TIMID", SPEC,
        ["MOVE_PSYCHIC", "MOVE_AIR_CUTTER", "MOVE_CALM_MIND", "MOVE_ROOST"],
        "ABILITY_MAGIC_BOUNCE"),
    mon("SPECIES_SKARMORY", 39, "ITEM_ORAN_BERRY", "NATURE_IMPISH", WALL_D,
        ["MOVE_SPIKES", "MOVE_STEEL_WING", "MOVE_DRILL_PECK", "MOVE_WHIRLWIND"],
        "ABILITY_STURDY"),
    mon("SPECIES_TROPIUS", 40, "ITEM_SITRUS_BERRY", "NATURE_CAREFUL", WALL_S,
        ["MOVE_MAGICAL_LEAF", "MOVE_AIR_CUTTER", "MOVE_GROWTH", "MOVE_SYNTHESIS"],
        "ABILITY_CHLOROPHYLL"),
    mon("SPECIES_ALTARIA", 41, "ITEM_SITRUS_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_DRAGON_DANCE", "MOVE_DRAGON_BREATH", "MOVE_AERIAL_ACE", "MOVE_ROOST"],
        "ABILITY_NATURAL_CURE"),
])

BOSSES["TRAINER_TATE_AND_LIZA_1"] = (AI_BOSS, [
    mon("SPECIES_GRUMPIG", 46, "ITEM_SITRUS_BERRY", "NATURE_CALM", WALL_S,
        ["MOVE_PSYCHIC", "MOVE_REFLECT", "MOVE_LIGHT_SCREEN", "MOVE_TAUNT"],
        "ABILITY_THICK_FAT"),
    mon("SPECIES_MEDICHAM", 47, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_FAKE_OUT", "MOVE_ZEN_HEADBUTT", "MOVE_BRICK_BREAK", "MOVE_ICE_PUNCH"],
        "ABILITY_PURE_POWER"),
    mon("SPECIES_CLAYDOL", 47, "ITEM_ORAN_BERRY", "NATURE_QUIET", MIXED_B,
        ["MOVE_EARTHQUAKE", "MOVE_PSYCHIC", "MOVE_ANCIENT_POWER", "MOVE_EXPLOSION"],
        "ABILITY_LEVITATE"),
    mon("SPECIES_SOLROCK", 48, "ITEM_ORAN_BERRY", "NATURE_BRAVE", BULK_P,
        ["MOVE_SUNNY_DAY", "MOVE_ROCK_SLIDE", "MOVE_ZEN_HEADBUTT", "MOVE_WILL_O_WISP"],
        "ABILITY_LEVITATE"),
    mon("SPECIES_LUNATONE", 48, "ITEM_ORAN_BERRY", "NATURE_QUIET", BULK_S,
        ["MOVE_CALM_MIND", "MOVE_PSYCHIC", "MOVE_ICE_BEAM", "MOVE_HYPNOSIS"],
        "ABILITY_LEVITATE"),
    mon("SPECIES_BRONZONG", 49, "ITEM_MACHO_BRACE", "NATURE_BRAVE", BULK_P,
        ["MOVE_TRICK_ROOM", "MOVE_GYRO_BALL", "MOVE_ZEN_HEADBUTT", "MOVE_HYPNOSIS"],
        "ABILITY_LEVITATE"),
])

BOSSES["TRAINER_JUAN_1"] = (AI_BOSS, [
    mon("SPECIES_POLITOED", 50, "ITEM_DAMP_ROCK", "NATURE_BOLD", WALL_D,
        ["MOVE_HYPNOSIS", "MOVE_SURF", "MOVE_PERISH_SONG", "MOVE_PROTECT"],
        "ABILITY_DRIZZLE"),
    mon("SPECIES_LUDICOLO", 50, "ITEM_ORAN_BERRY", "NATURE_MODEST", SPEC,
        ["MOVE_FAKE_OUT", "MOVE_GIGA_DRAIN", "MOVE_SURF", "MOVE_ICE_BEAM"],
        "ABILITY_SWIFT_SWIM"),
    mon("SPECIES_WHISCASH", 50, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_EARTHQUAKE", "MOVE_WATERFALL", "MOVE_AMNESIA", "MOVE_REST"],
        "ABILITY_OBLIVIOUS"),
    mon("SPECIES_CRAWDAUNT", 51, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_SWORDS_DANCE", "MOVE_CRABHAMMER", "MOVE_KNOCK_OFF", "MOVE_AQUA_JET"],
        "ABILITY_HYPER_CUTTER"),
    mon("SPECIES_WALREIN", 51, "ITEM_ORAN_BERRY", "NATURE_MODEST", BULK_S,
        ["MOVE_SURF", "MOVE_ICE_BEAM", "MOVE_BODY_SLAM", "MOVE_YAWN"],
        "ABILITY_THICK_FAT"),
    mon("SPECIES_KINGDRA", 53, "ITEM_SITRUS_BERRY", "NATURE_MODEST", SPEC,
        ["MOVE_SURF", "MOVE_DRAGON_PULSE", "MOVE_ICE_BEAM", "MOVE_RAIN_DANCE"],
        "ABILITY_SWIFT_SWIM"),
])

# ---------------------------------------------------------------------------
# Elite Four (loop-0 baselines; Victory Road boosted max is 54) + Champion.
# ---------------------------------------------------------------------------

BOSSES["TRAINER_SIDNEY"] = (AI_TOP, [
    mon("SPECIES_MIGHTYENA", 57, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_SUCKER_PUNCH", "MOVE_CRUNCH", "MOVE_ICE_FANG", "MOVE_HOWL"],
        "ABILITY_INTIMIDATE"),
    mon("SPECIES_SHIFTRY", 57, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_FAKE_OUT", "MOVE_LEAF_BLADE", "MOVE_SUCKER_PUNCH", "MOVE_EXTRASENSORY"],
        "ABILITY_CHLOROPHYLL"),
    mon("SPECIES_CACTURNE", 58, "ITEM_FOCUS_SASH", "NATURE_ADAMANT", PHYS,
        ["MOVE_SUCKER_PUNCH", "MOVE_NEEDLE_ARM", "MOVE_LEECH_SEED", "MOVE_SPIKES"],
        "ABILITY_SAND_VEIL"),
    mon("SPECIES_CRAWDAUNT", 58, "ITEM_MYSTIC_WATER", "NATURE_ADAMANT", PHYS,
        ["MOVE_SWORDS_DANCE", "MOVE_CRABHAMMER", "MOVE_KNOCK_OFF", "MOVE_AQUA_JET"],
        "ABILITY_HYPER_CUTTER"),
    mon("SPECIES_SABLEYE", 58, "ITEM_LEFTOVERS", "NATURE_CALM", WALL_S,
        ["MOVE_WILL_O_WISP", "MOVE_TAUNT", "MOVE_RECOVER", "MOVE_FOUL_PLAY"],
        "ABILITY_PRANKSTER"),
    mon("SPECIES_ABSOL", 59, "ITEM_SCOPE_LENS", "NATURE_JOLLY", PHYS,
        ["MOVE_SWORDS_DANCE", "MOVE_NIGHT_SLASH", "MOVE_PSYCHO_CUT", "MOVE_SUCKER_PUNCH"],
        "ABILITY_SUPER_LUCK"),
])

BOSSES["TRAINER_PHOEBE"] = (AI_TOP, [
    mon("SPECIES_DUSCLOPS", 58, "ITEM_EVIOLITE", "NATURE_IMPISH", MIXED_B,
        ["MOVE_WILL_O_WISP", "MOVE_SHADOW_PUNCH", "MOVE_ICE_PUNCH", "MOVE_PAIN_SPLIT"],
        "ABILITY_PRESSURE"),
    mon("SPECIES_BANETTE", 58, "ITEM_FOCUS_SASH", "NATURE_ADAMANT", PHYS,
        ["MOVE_SHADOW_CLAW", "MOVE_SUCKER_PUNCH", "MOVE_WILL_O_WISP", "MOVE_DESTINY_BOND"],
        "ABILITY_INSOMNIA"),
    mon("SPECIES_SHEDINJA", 58, "ITEM_LUM_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_SHADOW_SNEAK", "MOVE_X_SCISSOR", "MOVE_SHADOW_CLAW", "MOVE_GRUDGE"],
        "ABILITY_WONDER_GUARD"),
    mon("SPECIES_CLAYDOL", 59, "ITEM_LEFTOVERS", "NATURE_QUIET", MIXED_B,
        ["MOVE_STEALTH_ROCK", "MOVE_EARTHQUAKE", "MOVE_PSYCHIC", "MOVE_RAPID_SPIN"],
        "ABILITY_LEVITATE"),
    mon("SPECIES_MISMAGIUS", 59, "ITEM_SITRUS_BERRY", "NATURE_TIMID", SPEC,
        ["MOVE_SHADOW_BALL", "MOVE_THUNDERBOLT", "MOVE_NASTY_PLOT", "MOVE_TAUNT"],
        "ABILITY_LEVITATE"),
    mon("SPECIES_DUSKNOIR", 60, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_SHADOW_SNEAK", "MOVE_ICE_PUNCH", "MOVE_EARTHQUAKE", "MOVE_WILL_O_WISP"],
        "ABILITY_PRESSURE"),
])

BOSSES["TRAINER_GLACIA"] = (AI_TOP, [
    mon("SPECIES_ABOMASNOW", 59, "ITEM_ICY_ROCK", "NATURE_QUIET", BULK_S,
        ["MOVE_BLIZZARD", "MOVE_WOOD_HAMMER", "MOVE_ICE_SHARD", "MOVE_LEECH_SEED"],
        "ABILITY_SNOW_WARNING"),
    mon("SPECIES_GLALIE", 60, "ITEM_ORAN_BERRY", "NATURE_TIMID", SPEC,
        ["MOVE_BLIZZARD", "MOVE_CRUNCH", "MOVE_SPIKES", "MOVE_TAUNT"],
        "ABILITY_INNER_FOCUS"),
    mon("SPECIES_FROSLASS", 60, "ITEM_FOCUS_SASH", "NATURE_TIMID", SPEC,
        ["MOVE_BLIZZARD", "MOVE_SHADOW_BALL", "MOVE_THUNDER_WAVE", "MOVE_DESTINY_BOND"],
        "ABILITY_SNOW_CLOAK"),
    mon("SPECIES_SEALEO", 60, "ITEM_EVIOLITE", "NATURE_BOLD", WALL_D,
        ["MOVE_SURF", "MOVE_ICE_BEAM", "MOVE_ENCORE", "MOVE_REST"],
        "ABILITY_THICK_FAT"),
    mon("SPECIES_LUDICOLO", 60, "ITEM_LEFTOVERS", "NATURE_CALM", WALL_S,
        ["MOVE_FAKE_OUT", "MOVE_GIGA_DRAIN", "MOVE_SURF", "MOVE_ICE_BEAM"],
        "ABILITY_RAIN_DISH"),
    mon("SPECIES_WALREIN", 61, "ITEM_CHESTO_BERRY", "NATURE_MODEST", BULK_S,
        ["MOVE_SURF", "MOVE_BLIZZARD", "MOVE_BODY_SLAM", "MOVE_REST"],
        "ABILITY_THICK_FAT"),
])

BOSSES["TRAINER_DRAKE"] = (AI_TOP, [
    mon("SPECIES_SHELGON", 60, "ITEM_EVIOLITE", "NATURE_ADAMANT", BULK_P,
        ["MOVE_DRAGON_DANCE", "MOVE_DRAGON_CLAW", "MOVE_BRICK_BREAK", "MOVE_PROTECT"],
        "ABILITY_ROCK_HEAD"),
    mon("SPECIES_ALTARIA", 60, "ITEM_SITRUS_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_DRAGON_DANCE", "MOVE_DRAGON_CLAW", "MOVE_EARTHQUAKE", "MOVE_ROOST"],
        "ABILITY_NATURAL_CURE"),
    mon("SPECIES_FLYGON", 61, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_EARTHQUAKE", "MOVE_DRAGON_CLAW", "MOVE_ROCK_SLIDE", "MOVE_U_TURN"],
        "ABILITY_LEVITATE"),
    mon("SPECIES_KINGDRA", 61, "ITEM_LUM_BERRY", "NATURE_MODEST", SPEC,
        ["MOVE_SURF", "MOVE_DRAGON_PULSE", "MOVE_ICE_BEAM", "MOVE_AGILITY"],
        "ABILITY_SWIFT_SWIM"),
    mon("SPECIES_GARCHOMP", 61, "ITEM_ROCKY_HELMET", "NATURE_JOLLY", PHYS,
        ["MOVE_EARTHQUAKE", "MOVE_DRAGON_CLAW", "MOVE_ROCK_SLIDE", "MOVE_SWORDS_DANCE"],
        "ABILITY_ROUGH_SKIN"),
    mon("SPECIES_SALAMENCE", 62, "ITEM_LUM_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_DRAGON_DANCE", "MOVE_OUTRAGE", "MOVE_EARTHQUAKE", "MOVE_AERIAL_ACE"],
        "ABILITY_INTIMIDATE"),
])

BOSSES["TRAINER_WALLACE"] = (AI_TOP, [
    mon("SPECIES_WAILORD", 62, "ITEM_CHOICE_SCARF", "NATURE_MODEST", SPEC,
        ["MOVE_WATER_SPOUT", "MOVE_HYPER_VOICE", "MOVE_ICE_BEAM", "MOVE_HYDRO_PUMP"],
        "ABILITY_PRESSURE"),
    mon("SPECIES_TENTACRUEL", 62, "ITEM_BLACK_SLUDGE", "NATURE_TIMID", SPEC,
        ["MOVE_TOXIC_SPIKES", "MOVE_SLUDGE_BOMB", "MOVE_SURF", "MOVE_ICE_BEAM"],
        "ABILITY_LIQUID_OOZE"),
    mon("SPECIES_LUDICOLO", 63, "ITEM_DAMP_ROCK", "NATURE_MODEST", SPEC,
        ["MOVE_RAIN_DANCE", "MOVE_GIGA_DRAIN", "MOVE_HYDRO_PUMP", "MOVE_ICE_BEAM"],
        "ABILITY_SWIFT_SWIM"),
    mon("SPECIES_WHISCASH", 63, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_EARTHQUAKE", "MOVE_WATERFALL", "MOVE_ICE_BEAM", "MOVE_AMNESIA"],
        "ABILITY_OBLIVIOUS"),
    mon("SPECIES_GYARADOS", 63, "ITEM_LUM_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_DRAGON_DANCE", "MOVE_WATERFALL", "MOVE_EARTHQUAKE", "MOVE_ICE_FANG"],
        "ABILITY_INTIMIDATE"),
    mon("SPECIES_MILOTIC", 65, "ITEM_LEFTOVERS", "NATURE_BOLD", WALL_D,
        ["MOVE_SURF", "MOVE_ICE_BEAM", "MOVE_RECOVER", "MOVE_TOXIC"],
        "ABILITY_MARVEL_SCALE"),
])

# Steven (Meteor Falls superboss, post-game).
BOSSES["TRAINER_STEVEN"] = (AI_TOP, [
    mon("SPECIES_SKARMORY", 80, "ITEM_ROCKY_HELMET", "NATURE_IMPISH", WALL_D,
        ["MOVE_SPIKES", "MOVE_DRILL_PECK", "MOVE_WHIRLWIND", "MOVE_ROOST"],
        "ABILITY_STURDY"),
    mon("SPECIES_CLAYDOL", 80, "ITEM_LEFTOVERS", "NATURE_BOLD", MIXED_B,
        ["MOVE_STEALTH_ROCK", "MOVE_EARTH_POWER", "MOVE_PSYCHIC", "MOVE_RAPID_SPIN"],
        "ABILITY_LEVITATE"),
    mon("SPECIES_CRADILY", 81, "ITEM_LEFTOVERS", "NATURE_CAREFUL", WALL_S,
        ["MOVE_GIGA_DRAIN", "MOVE_ROCK_SLIDE", "MOVE_RECOVER", "MOVE_TOXIC"],
        "ABILITY_SUCTION_CUPS"),
    mon("SPECIES_ARMALDO", 81, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_SWORDS_DANCE", "MOVE_X_SCISSOR", "MOVE_ROCK_BLAST", "MOVE_AQUA_JET"],
        "ABILITY_BATTLE_ARMOR"),
    mon("SPECIES_AGGRON", 82, "ITEM_CHOICE_BAND", "NATURE_ADAMANT", PHYS,
        ["MOVE_HEAD_SMASH", "MOVE_IRON_HEAD", "MOVE_EARTHQUAKE", "MOVE_ICE_PUNCH"],
        "ABILITY_ROCK_HEAD"),
    mon("SPECIES_METAGROSS", 84, "ITEM_LUM_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_METEOR_MASH", "MOVE_ZEN_HEADBUTT", "MOVE_BULLET_PUNCH", "MOVE_EARTHQUAKE"],
        "ABILITY_CLEAR_BODY"),
])

# ---------------------------------------------------------------------------
# Team Magma / Team Aqua admins and leaders.
# ---------------------------------------------------------------------------

BOSSES["TRAINER_TABITHA_MT_CHIMNEY"] = (AI_BOSS, [
    mon("SPECIES_NUMEL", 27, "ITEM_ORAN_BERRY", "NATURE_QUIET", BULK_S,
        ["MOVE_FLAME_BURST", "MOVE_BULLDOZE", "MOVE_AMNESIA", "MOVE_YAWN"]),
    mon("SPECIES_GOLBAT", 28, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_WING_ATTACK", "MOVE_BITE", "MOVE_CONFUSE_RAY", "MOVE_TOXIC"],
        "ABILITY_INNER_FOCUS"),
    mon("SPECIES_MIGHTYENA", 28, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_BITE", "MOVE_SWAGGER", "MOVE_SAND_ATTACK", "MOVE_HOWL"],
        "ABILITY_INTIMIDATE"),
    mon("SPECIES_BALTOY", 28, "ITEM_ORAN_BERRY", "NATURE_QUIET", BULK_S,
        ["MOVE_PSYBEAM", "MOVE_BULLDOZE", "MOVE_RAPID_SPIN", "MOVE_ROCK_TOMB"],
        "ABILITY_LEVITATE"),
    mon("SPECIES_SLUGMA", 28, "ITEM_ORAN_BERRY", "NATURE_BOLD", BULK_S,
        ["MOVE_FLAME_BURST", "MOVE_ROCK_TOMB", "MOVE_YAWN", "MOVE_LIGHT_SCREEN"],
        "ABILITY_FLAME_BODY"),
    mon("SPECIES_CAMERUPT", 29, "ITEM_SITRUS_BERRY", "NATURE_QUIET", BULK_S,
        ["MOVE_FLAME_BURST", "MOVE_BULLDOZE", "MOVE_ROCK_TOMB", "MOVE_AMNESIA"]),
])

BOSSES["TRAINER_MAXIE_MT_CHIMNEY"] = (AI_BOSS, [
    mon("SPECIES_MIGHTYENA", 29, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_BITE", "MOVE_SWAGGER", "MOVE_QUICK_ATTACK", "MOVE_HOWL"],
        "ABILITY_INTIMIDATE"),
    mon("SPECIES_GOLBAT", 29, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_WING_ATTACK", "MOVE_BITE", "MOVE_CONFUSE_RAY", "MOVE_TOXIC"],
        "ABILITY_INNER_FOCUS"),
    mon("SPECIES_HOUNDOUR", 30, "ITEM_ORAN_BERRY", "NATURE_TIMID", SPEC,
        ["MOVE_FLAME_BURST", "MOVE_BITE", "MOVE_ROAR", "MOVE_TAUNT"],
        "ABILITY_FLASH_FIRE"),
    mon("SPECIES_LAIRON", 30, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_IRON_HEAD", "MOVE_ROCK_TOMB", "MOVE_PROTECT", "MOVE_ROAR"],
        "ABILITY_STURDY"),
    mon("SPECIES_TORKOAL", 30, "ITEM_WHITE_HERB", "NATURE_BOLD", WALL_D,
        ["MOVE_OVERHEAT", "MOVE_BODY_SLAM", "MOVE_YAWN", "MOVE_IRON_DEFENSE"],
        "ABILITY_WHITE_SMOKE"),
    mon("SPECIES_CAMERUPT", 31, "ITEM_SITRUS_BERRY", "NATURE_QUIET", BULK_S,
        ["MOVE_FLAME_BURST", "MOVE_BULLDOZE", "MOVE_ROCK_TOMB", "MOVE_YAWN"]),
])

BOSSES["TRAINER_TABITHA_MAGMA_HIDEOUT"] = (AI_BOSS, [
    mon("SPECIES_MIGHTYENA", 36, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_CRUNCH", "MOVE_SUCKER_PUNCH", "MOVE_SWAGGER", "MOVE_HOWL"],
        "ABILITY_INTIMIDATE"),
    mon("SPECIES_GOLBAT", 36, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_AIR_CUTTER", "MOVE_BITE", "MOVE_CONFUSE_RAY", "MOVE_TOXIC"],
        "ABILITY_INNER_FOCUS"),
    mon("SPECIES_LAIRON", 37, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_IRON_HEAD", "MOVE_ROCK_SLIDE", "MOVE_PROTECT", "MOVE_ROAR"],
        "ABILITY_STURDY"),
    mon("SPECIES_TORKOAL", 37, "ITEM_WHITE_HERB", "NATURE_BOLD", WALL_D,
        ["MOVE_OVERHEAT", "MOVE_BODY_SLAM", "MOVE_YAWN", "MOVE_IRON_DEFENSE"],
        "ABILITY_WHITE_SMOKE"),
    mon("SPECIES_HOUNDOOM", 37, "ITEM_ORAN_BERRY", "NATURE_TIMID", SPEC,
        ["MOVE_FLAMETHROWER", "MOVE_BITE", "MOVE_SOLAR_BEAM", "MOVE_TAUNT"],
        "ABILITY_FLASH_FIRE"),
    mon("SPECIES_CAMERUPT", 38, "ITEM_SITRUS_BERRY", "NATURE_QUIET", BULK_S,
        ["MOVE_FLAMETHROWER", "MOVE_EARTH_POWER", "MOVE_ROCK_SLIDE", "MOVE_AMNESIA"]),
])

BOSSES["TRAINER_MAXIE_MAGMA_HIDEOUT"] = (AI_BOSS, [
    mon("SPECIES_MIGHTYENA", 38, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_CRUNCH", "MOVE_SUCKER_PUNCH", "MOVE_ICE_FANG", "MOVE_HOWL"],
        "ABILITY_INTIMIDATE"),
    mon("SPECIES_CROBAT", 38, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_AIR_CUTTER", "MOVE_BITE", "MOVE_CONFUSE_RAY", "MOVE_TOXIC"],
        "ABILITY_INNER_FOCUS"),
    mon("SPECIES_HOUNDOOM", 39, "ITEM_ORAN_BERRY", "NATURE_TIMID", SPEC,
        ["MOVE_FLAMETHROWER", "MOVE_DARK_PULSE", "MOVE_SOLAR_BEAM", "MOVE_NASTY_PLOT"],
        "ABILITY_FLASH_FIRE"),
    mon("SPECIES_LAIRON", 39, "ITEM_EVIOLITE", "NATURE_ADAMANT", BULK_P,
        ["MOVE_IRON_HEAD", "MOVE_ROCK_SLIDE", "MOVE_BULLDOZE", "MOVE_PROTECT"],
        "ABILITY_STURDY"),
    mon("SPECIES_CLAYDOL", 39, "ITEM_ORAN_BERRY", "NATURE_QUIET", MIXED_B,
        ["MOVE_EARTHQUAKE", "MOVE_PSYCHIC", "MOVE_LIGHT_SCREEN", "MOVE_RAPID_SPIN"],
        "ABILITY_LEVITATE"),
    mon("SPECIES_CAMERUPT", 40, "ITEM_WHITE_HERB", "NATURE_QUIET", BULK_S,
        ["MOVE_OVERHEAT", "MOVE_EARTH_POWER", "MOVE_ROCK_SLIDE", "MOVE_YAWN"]),
])

BOSSES["TRAINER_TABITHA_MOSSDEEP"] = (AI_BOSS, [
    mon("SPECIES_MIGHTYENA", 39, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_CRUNCH", "MOVE_SUCKER_PUNCH", "MOVE_SWAGGER", "MOVE_HOWL"],
        "ABILITY_INTIMIDATE"),
    mon("SPECIES_CROBAT", 39, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_AIR_CUTTER", "MOVE_CROSS_POISON", "MOVE_CONFUSE_RAY", "MOVE_BITE"],
        "ABILITY_INNER_FOCUS"),
    mon("SPECIES_TORKOAL", 40, "ITEM_WHITE_HERB", "NATURE_BOLD", WALL_D,
        ["MOVE_OVERHEAT", "MOVE_BODY_SLAM", "MOVE_YAWN", "MOVE_IRON_DEFENSE"],
        "ABILITY_WHITE_SMOKE"),
    mon("SPECIES_CLAYDOL", 40, "ITEM_ORAN_BERRY", "NATURE_QUIET", MIXED_B,
        ["MOVE_EARTHQUAKE", "MOVE_PSYCHIC", "MOVE_ROCK_TOMB", "MOVE_RAPID_SPIN"],
        "ABILITY_LEVITATE"),
    mon("SPECIES_MAGCARGO", 40, "ITEM_ORAN_BERRY", "NATURE_BOLD", BULK_S,
        ["MOVE_FLAMETHROWER", "MOVE_ROCK_SLIDE", "MOVE_YAWN", "MOVE_LIGHT_SCREEN"],
        "ABILITY_FLAME_BODY"),
    mon("SPECIES_CAMERUPT", 41, "ITEM_SITRUS_BERRY", "NATURE_QUIET", BULK_S,
        ["MOVE_FLAMETHROWER", "MOVE_EARTH_POWER", "MOVE_ROCK_SLIDE", "MOVE_AMNESIA"]),
])

BOSSES["TRAINER_MAXIE_MOSSDEEP"] = (AI_BOSS, [
    mon("SPECIES_MIGHTYENA", 41, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_CRUNCH", "MOVE_SUCKER_PUNCH", "MOVE_ICE_FANG", "MOVE_HOWL"],
        "ABILITY_INTIMIDATE"),
    mon("SPECIES_CROBAT", 41, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_CROSS_POISON", "MOVE_AIR_CUTTER", "MOVE_CONFUSE_RAY", "MOVE_TOXIC"],
        "ABILITY_INNER_FOCUS"),
    mon("SPECIES_HOUNDOOM", 42, "ITEM_ORAN_BERRY", "NATURE_TIMID", SPEC,
        ["MOVE_FLAMETHROWER", "MOVE_DARK_PULSE", "MOVE_SOLAR_BEAM", "MOVE_NASTY_PLOT"],
        "ABILITY_FLASH_FIRE"),
    mon("SPECIES_CLAYDOL", 42, "ITEM_ORAN_BERRY", "NATURE_QUIET", MIXED_B,
        ["MOVE_EARTHQUAKE", "MOVE_PSYCHIC", "MOVE_LIGHT_SCREEN", "MOVE_RAPID_SPIN"],
        "ABILITY_LEVITATE"),
    mon("SPECIES_AGGRON", 42, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_IRON_HEAD", "MOVE_ROCK_SLIDE", "MOVE_EARTHQUAKE", "MOVE_PROTECT"],
        "ABILITY_STURDY"),
    mon("SPECIES_CAMERUPT", 43, "ITEM_WHITE_HERB", "NATURE_QUIET", BULK_S,
        ["MOVE_OVERHEAT", "MOVE_EARTH_POWER", "MOVE_ROCK_SLIDE", "MOVE_YAWN"]),
])

BOSSES["TRAINER_SHELLY_WEATHER_INSTITUTE"] = (AI_BOSS, [
    mon("SPECIES_MIGHTYENA", 36, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_CRUNCH", "MOVE_SUCKER_PUNCH", "MOVE_SWAGGER", "MOVE_HOWL"],
        "ABILITY_INTIMIDATE"),
    mon("SPECIES_GOLBAT", 36, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_AIR_CUTTER", "MOVE_BITE", "MOVE_CONFUSE_RAY", "MOVE_TOXIC"],
        "ABILITY_INNER_FOCUS"),
    mon("SPECIES_PELIPPER", 37, "ITEM_DAMP_ROCK", "NATURE_MODEST", BULK_S,
        ["MOVE_WATER_PULSE", "MOVE_AIR_CUTTER", "MOVE_PROTECT", "MOVE_ROOST"],
        "ABILITY_DRIZZLE"),
    mon("SPECIES_WAILORD", 37, "ITEM_ORAN_BERRY", "NATURE_MODEST", BULK_S,
        ["MOVE_WATER_SPOUT", "MOVE_ICE_BEAM", "MOVE_BODY_SLAM", "MOVE_AMNESIA"],
        "ABILITY_PRESSURE"),
    mon("SPECIES_SEADRA", 37, "ITEM_EVIOLITE", "NATURE_MODEST", SPEC,
        ["MOVE_WATER_PULSE", "MOVE_TWISTER", "MOVE_ICE_BEAM", "MOVE_AGILITY"],
        "ABILITY_SNIPER"),
    mon("SPECIES_SHARPEDO", 38, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_CRUNCH", "MOVE_WATERFALL", "MOVE_ICE_FANG", "MOVE_SCREECH"],
        "ABILITY_ROUGH_SKIN"),
])

BOSSES["TRAINER_MATT"] = (AI_BOSS, [
    mon("SPECIES_MIGHTYENA", 39, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_CRUNCH", "MOVE_SUCKER_PUNCH", "MOVE_SWAGGER", "MOVE_HOWL"],
        "ABILITY_INTIMIDATE"),
    mon("SPECIES_GOLBAT", 39, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_AIR_CUTTER", "MOVE_CROSS_POISON", "MOVE_CONFUSE_RAY", "MOVE_BITE"],
        "ABILITY_INNER_FOCUS"),
    mon("SPECIES_MUK", 40, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_SLUDGE_BOMB", "MOVE_SHADOW_SNEAK", "MOVE_MINIMIZE", "MOVE_TOXIC"],
        "ABILITY_STICKY_HOLD"),
    mon("SPECIES_WAILORD", 40, "ITEM_ORAN_BERRY", "NATURE_MODEST", BULK_S,
        ["MOVE_WATER_SPOUT", "MOVE_ICE_BEAM", "MOVE_BODY_SLAM", "MOVE_AMNESIA"],
        "ABILITY_PRESSURE"),
    mon("SPECIES_WHISCASH", 40, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_EARTHQUAKE", "MOVE_WATERFALL", "MOVE_AMNESIA", "MOVE_REST"],
        "ABILITY_OBLIVIOUS"),
    mon("SPECIES_SHARPEDO", 41, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_CRUNCH", "MOVE_WATERFALL", "MOVE_ICE_FANG", "MOVE_SCREECH"],
        "ABILITY_ROUGH_SKIN"),
])

BOSSES["TRAINER_SHELLY_SEAFLOOR_CAVERN"] = (AI_BOSS, [
    mon("SPECIES_MIGHTYENA", 44, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_CRUNCH", "MOVE_SUCKER_PUNCH", "MOVE_ICE_FANG", "MOVE_HOWL"],
        "ABILITY_INTIMIDATE"),
    mon("SPECIES_CROBAT", 44, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_CROSS_POISON", "MOVE_AIR_CUTTER", "MOVE_CONFUSE_RAY", "MOVE_TOXIC"],
        "ABILITY_INNER_FOCUS"),
    mon("SPECIES_PELIPPER", 44, "ITEM_DAMP_ROCK", "NATURE_MODEST", BULK_S,
        ["MOVE_HYDRO_PUMP", "MOVE_AIR_CUTTER", "MOVE_PROTECT", "MOVE_ROOST"],
        "ABILITY_DRIZZLE"),
    mon("SPECIES_WAILORD", 45, "ITEM_ORAN_BERRY", "NATURE_MODEST", BULK_S,
        ["MOVE_WATER_SPOUT", "MOVE_ICE_BEAM", "MOVE_HYPER_VOICE", "MOVE_AMNESIA"],
        "ABILITY_PRESSURE"),
    mon("SPECIES_HUNTAIL", 45, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_WATERFALL", "MOVE_CRUNCH", "MOVE_ICE_FANG", "MOVE_IRON_DEFENSE"],
        "ABILITY_SWIFT_SWIM"),
    mon("SPECIES_SHARPEDO", 46, "ITEM_FOCUS_SASH", "NATURE_ADAMANT", PHYS,
        ["MOVE_CRUNCH", "MOVE_WATERFALL", "MOVE_ICE_FANG", "MOVE_AQUA_JET"],
        "ABILITY_ROUGH_SKIN"),
])

BOSSES["TRAINER_ARCHIE"] = (AI_TOP, [
    mon("SPECIES_MIGHTYENA", 46, "ITEM_SITRUS_BERRY", "NATURE_ADAMANT", PHYS,
        ["MOVE_CRUNCH", "MOVE_SUCKER_PUNCH", "MOVE_ICE_FANG", "MOVE_HOWL"],
        "ABILITY_INTIMIDATE"),
    mon("SPECIES_CROBAT", 46, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_CROSS_POISON", "MOVE_AIR_CUTTER", "MOVE_CONFUSE_RAY", "MOVE_TOXIC"],
        "ABILITY_INNER_FOCUS"),
    mon("SPECIES_MUK", 46, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", BULK_P,
        ["MOVE_SLUDGE_BOMB", "MOVE_SHADOW_SNEAK", "MOVE_MINIMIZE", "MOVE_TOXIC"],
        "ABILITY_STICKY_HOLD"),
    mon("SPECIES_WAILORD", 47, "ITEM_ORAN_BERRY", "NATURE_MODEST", BULK_S,
        ["MOVE_WATER_SPOUT", "MOVE_ICE_BEAM", "MOVE_HYPER_VOICE", "MOVE_AMNESIA"],
        "ABILITY_PRESSURE"),
    mon("SPECIES_TENTACRUEL", 47, "ITEM_BLACK_SLUDGE", "NATURE_TIMID", SPEC,
        ["MOVE_TOXIC_SPIKES", "MOVE_SLUDGE_BOMB", "MOVE_SURF", "MOVE_ICE_BEAM"],
        "ABILITY_LIQUID_OOZE"),
    mon("SPECIES_SHARPEDO", 48, "ITEM_FOCUS_SASH", "NATURE_ADAMANT", PHYS,
        ["MOVE_CRUNCH", "MOVE_WATERFALL", "MOVE_ICE_FANG", "MOVE_AQUA_JET"],
        "ABILITY_ROUGH_SKIN"),
])

# ---------------------------------------------------------------------------
# Wally.
# ---------------------------------------------------------------------------

BOSSES["TRAINER_WALLY_MAUVILLE"] = (AI_BOSS, [
    mon("SPECIES_TAILLOW", 17, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_WING_ATTACK", "MOVE_QUICK_ATTACK", "MOVE_GROWL", "MOVE_DOUBLE_TEAM"],
        "ABILITY_GUTS"),
    mon("SPECIES_ZIGZAGOON", 17, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_HEADBUTT", "MOVE_SAND_ATTACK", "MOVE_PIN_MISSILE", "MOVE_MUD_SPORT"],
        "ABILITY_PICKUP"),
    mon("SPECIES_KIRLIA", 19, "ITEM_SITRUS_BERRY", "NATURE_MODEST", SPEC,
        ["MOVE_CONFUSION", "MOVE_MAGICAL_LEAF", "MOVE_CALM_MIND", "MOVE_DOUBLE_TEAM"],
        "ABILITY_TRACE"),
])

BOSSES["TRAINER_WALLY_VR_1"] = (AI_TOP, [
    mon("SPECIES_ALTARIA", 54, "ITEM_SITRUS_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_DRAGON_DANCE", "MOVE_DRAGON_CLAW", "MOVE_AERIAL_ACE", "MOVE_ROOST"],
        "ABILITY_NATURAL_CURE"),
    mon("SPECIES_DELCATTY", 54, "ITEM_SITRUS_BERRY", "NATURE_BOLD", WALL_D,
        ["MOVE_FAKE_OUT", "MOVE_SING", "MOVE_WISH", "MOVE_COVET"],
        "ABILITY_CUTE_CHARM"),
    mon("SPECIES_ROSELIA", 55, "ITEM_EVIOLITE", "NATURE_TIMID", SPEC,
        ["MOVE_GIGA_DRAIN", "MOVE_SLUDGE_BOMB", "MOVE_SPIKES", "MOVE_SYNTHESIS"],
        "ABILITY_NATURAL_CURE"),
    mon("SPECIES_MAGNETON", 55, "ITEM_EVIOLITE", "NATURE_MODEST", BULK_S,
        ["MOVE_THUNDERBOLT", "MOVE_FLASH_CANNON", "MOVE_THUNDER_WAVE", "MOVE_LIGHT_SCREEN"],
        "ABILITY_STURDY"),
    mon("SPECIES_FLYGON", 56, "ITEM_LUM_BERRY", "NATURE_JOLLY", PHYS,
        ["MOVE_EARTHQUAKE", "MOVE_DRAGON_CLAW", "MOVE_ROCK_SLIDE", "MOVE_U_TURN"],
        "ABILITY_LEVITATE"),
    mon("SPECIES_GARDEVOIR", 57, "ITEM_LEFTOVERS", "NATURE_TIMID", SPEC,
        ["MOVE_CALM_MIND", "MOVE_PSYCHIC", "MOVE_THUNDERBOLT", "MOVE_HYPNOSIS"],
        "ABILITY_TRACE"),
])

# ---------------------------------------------------------------------------
# Rivals. The trainer ID suffix is the PLAYER's starter; the rival carries
# the counter-starter. Stages ramp 3 -> 4 -> 5 -> 6 -> 6.
# ---------------------------------------------------------------------------

STARTER_FOR_SUFFIX = {"TREECKO": "TORCHIC", "TORCHIC": "MUDKIP", "MUDKIP": "TREECKO"}

STARTER_STAGES = {
    # stage: (level, {rival_starter_family: mon})
    "R103": 9, "RUSTBORO": 16, "R110": 24, "R119": 37, "LILYCOVE": 41,
}


def starter_mon(family, stage):
    lv = STARTER_STAGES[stage]
    if family == "TORCHIC":
        forms = {"R103": "SPECIES_TORCHIC", "RUSTBORO": "SPECIES_COMBUSKEN",
                 "R110": "SPECIES_COMBUSKEN", "R119": "SPECIES_BLAZIKEN",
                 "LILYCOVE": "SPECIES_BLAZIKEN"}
        moves = {
            "R103": ["MOVE_EMBER", "MOVE_SCRATCH", "MOVE_GROWL", "MOVE_SAND_ATTACK"],
            "RUSTBORO": ["MOVE_EMBER", "MOVE_DOUBLE_KICK", "MOVE_PECK", "MOVE_BULK_UP"],
            "R110": ["MOVE_FLAME_BURST", "MOVE_DOUBLE_KICK", "MOVE_AERIAL_ACE", "MOVE_BULK_UP"],
            "R119": ["MOVE_BLAZE_KICK", "MOVE_BRICK_BREAK", "MOVE_AERIAL_ACE", "MOVE_BULK_UP"],
            "LILYCOVE": ["MOVE_BLAZE_KICK", "MOVE_SKY_UPPERCUT", "MOVE_ROCK_SLIDE", "MOVE_BULK_UP"],
        }
        nature, evs = "NATURE_ADAMANT", PHYS
    elif family == "MUDKIP":
        forms = {"R103": "SPECIES_MUDKIP", "RUSTBORO": "SPECIES_MARSHTOMP",
                 "R110": "SPECIES_MARSHTOMP", "R119": "SPECIES_SWAMPERT",
                 "LILYCOVE": "SPECIES_SWAMPERT"}
        moves = {
            "R103": ["MOVE_WATER_GUN", "MOVE_TACKLE", "MOVE_GROWL", "MOVE_MUD_SLAP"],
            "RUSTBORO": ["MOVE_WATER_GUN", "MOVE_MUD_SHOT", "MOVE_ROCK_TOMB", "MOVE_PROTECT"],
            "R110": ["MOVE_WATER_PULSE", "MOVE_MUD_SHOT", "MOVE_ROCK_TOMB", "MOVE_PROTECT"],
            "R119": ["MOVE_MUDDY_WATER", "MOVE_EARTHQUAKE", "MOVE_ROCK_SLIDE", "MOVE_PROTECT"],
            "LILYCOVE": ["MOVE_MUDDY_WATER", "MOVE_EARTHQUAKE", "MOVE_ICE_BEAM", "MOVE_PROTECT"],
        }
        nature, evs = "NATURE_QUIET", MIXED_B
    else:  # TREECKO line
        forms = {"R103": "SPECIES_TREECKO", "RUSTBORO": "SPECIES_GROVYLE",
                 "R110": "SPECIES_GROVYLE", "R119": "SPECIES_SCEPTILE",
                 "LILYCOVE": "SPECIES_SCEPTILE"}
        moves = {
            "R103": ["MOVE_ABSORB", "MOVE_POUND", "MOVE_LEER", "MOVE_QUICK_ATTACK"],
            "RUSTBORO": ["MOVE_ABSORB", "MOVE_QUICK_ATTACK", "MOVE_PURSUIT", "MOVE_SCREECH"],
            "R110": ["MOVE_MEGA_DRAIN", "MOVE_QUICK_ATTACK", "MOVE_FURY_CUTTER", "MOVE_SCREECH"],
            "R119": ["MOVE_LEAF_BLADE", "MOVE_DRAGON_BREATH", "MOVE_THUNDER_PUNCH", "MOVE_AGILITY"],
            "LILYCOVE": ["MOVE_LEAF_BLADE", "MOVE_DRAGON_CLAW", "MOVE_THUNDER_PUNCH", "MOVE_AGILITY"],
        }
        nature, evs = "NATURE_JOLLY", PHYS
    item = {"R103": "ITEM_ORAN_BERRY", "RUSTBORO": "ITEM_ORAN_BERRY",
            "R110": "ITEM_SITRUS_BERRY", "R119": "ITEM_SITRUS_BERRY",
            "LILYCOVE": "ITEM_SITRUS_BERRY"}[stage]
    return mon(forms[stage], lv, item, nature, evs, moves[stage])


RIVAL_CORE = {
    "R103": [
        mon("SPECIES_ZIGZAGOON", 7, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
            ["MOVE_TACKLE", "MOVE_SAND_ATTACK", "MOVE_TAIL_WHIP", "MOVE_GROWL"],
            "ABILITY_PICKUP"),
        mon("SPECIES_WINGULL", 8, "ITEM_ORAN_BERRY", "NATURE_TIMID", SPEC,
            ["MOVE_WATER_GUN", "MOVE_GUST", "MOVE_GROWL", "MOVE_SUPERSONIC"]),
    ],
    "RUSTBORO": [
        mon("SPECIES_SLAKOTH", 14, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", BULK_P,
            ["MOVE_YAWN", "MOVE_HEADBUTT", "MOVE_ENCORE", "MOVE_SLACK_OFF"],
            "ABILITY_TRUANT"),
        mon("SPECIES_WINGULL", 15, "ITEM_ORAN_BERRY", "NATURE_TIMID", SPEC,
            ["MOVE_WATER_GUN", "MOVE_WING_ATTACK", "MOVE_SUPERSONIC", "MOVE_QUICK_ATTACK"]),
        mon("SPECIES_SHROOMISH", 15, "ITEM_ORAN_BERRY", "NATURE_BOLD", WALL_D,
            ["MOVE_STUN_SPORE", "MOVE_LEECH_SEED", "MOVE_MEGA_DRAIN", "MOVE_HEADBUTT"],
            "ABILITY_EFFECT_SPORE"),
    ],
    "R110": [
        mon("SPECIES_VIGOROTH", 22, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
            ["MOVE_SLASH", "MOVE_ENCORE", "MOVE_BULK_UP", "MOVE_FAINT_ATTACK"],
            "ABILITY_VITAL_SPIRIT"),
        mon("SPECIES_WINGULL", 22, "ITEM_ORAN_BERRY", "NATURE_TIMID", SPEC,
            ["MOVE_WATER_PULSE", "MOVE_WING_ATTACK", "MOVE_SUPERSONIC", "MOVE_QUICK_ATTACK"]),
        mon("SPECIES_MAGNEMITE", 22, "ITEM_ORAN_BERRY", "NATURE_MODEST", BULK_S,
            ["MOVE_THUNDER_WAVE", "MOVE_SPARK", "MOVE_MIRROR_SHOT", "MOVE_SUPERSONIC"],
            "ABILITY_STURDY"),
        mon("SPECIES_ARON", 23, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", BULK_P,
            ["MOVE_METAL_CLAW", "MOVE_ROCK_TOMB", "MOVE_HEADBUTT", "MOVE_PROTECT"],
            "ABILITY_STURDY"),
    ],
    "R119": [
        mon("SPECIES_SWELLOW", 34, "ITEM_ORAN_BERRY", "NATURE_JOLLY", PHYS,
            ["MOVE_AERIAL_ACE", "MOVE_QUICK_ATTACK", "MOVE_ENDEAVOR", "MOVE_DOUBLE_TEAM"],
            "ABILITY_GUTS"),
        mon("SPECIES_PELIPPER", 34, "ITEM_ORAN_BERRY", "NATURE_MODEST", BULK_S,
            ["MOVE_WATER_PULSE", "MOVE_AIR_CUTTER", "MOVE_PROTECT", "MOVE_SUPERSONIC"],
            "ABILITY_KEEN_EYE"),
        mon("SPECIES_MAGNETON", 35, "ITEM_ORAN_BERRY", "NATURE_MODEST", BULK_S,
            ["MOVE_SPARK", "MOVE_MIRROR_SHOT", "MOVE_THUNDER_WAVE", "MOVE_SCREECH"],
            "ABILITY_STURDY"),
        mon("SPECIES_BRELOOM", 35, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
            ["MOVE_STUN_SPORE", "MOVE_MACH_PUNCH", "MOVE_HEADBUTT", "MOVE_LEECH_SEED"],
            "ABILITY_EFFECT_SPORE"),
        mon("SPECIES_GRUMPIG", 36, "ITEM_SITRUS_BERRY", "NATURE_CALM", WALL_S,
            ["MOVE_PSYBEAM", "MOVE_REFLECT", "MOVE_LIGHT_SCREEN", "MOVE_CONFUSE_RAY"],
            "ABILITY_THICK_FAT"),
    ],
    "LILYCOVE": [
        mon("SPECIES_SWELLOW", 38, "ITEM_FLAME_ORB", "NATURE_JOLLY", PHYS,
            ["MOVE_FACADE", "MOVE_AERIAL_ACE", "MOVE_QUICK_ATTACK", "MOVE_ENDEAVOR"],
            "ABILITY_GUTS"),
        mon("SPECIES_PELIPPER", 38, "ITEM_DAMP_ROCK", "NATURE_MODEST", BULK_S,
            ["MOVE_WATER_PULSE", "MOVE_AIR_CUTTER", "MOVE_PROTECT", "MOVE_ROOST"],
            "ABILITY_DRIZZLE"),
        mon("SPECIES_MAGNETON", 39, "ITEM_EVIOLITE", "NATURE_MODEST", BULK_S,
            ["MOVE_THUNDERBOLT", "MOVE_MIRROR_SHOT", "MOVE_THUNDER_WAVE", "MOVE_SCREECH"],
            "ABILITY_STURDY"),
        mon("SPECIES_BRELOOM", 39, "ITEM_ORAN_BERRY", "NATURE_ADAMANT", PHYS,
            ["MOVE_SPORE", "MOVE_MACH_PUNCH", "MOVE_SEED_BOMB", "MOVE_LEECH_SEED"],
            "ABILITY_EFFECT_SPORE"),
        mon("SPECIES_TROPIUS", 39, "ITEM_SITRUS_BERRY", "NATURE_CAREFUL", WALL_S,
            ["MOVE_MAGICAL_LEAF", "MOVE_AIR_CUTTER", "MOVE_GROWTH", "MOVE_SYNTHESIS"],
            "ABILITY_CHLOROPHYLL"),
    ],
}

RIVAL_STAGE_FOR_ID = {"ROUTE_103": "R103", "RUSTBORO": "RUSTBORO",
                      "ROUTE_110": "R110", "ROUTE_119": "R119",
                      "LILYCOVE": "LILYCOVE"}

for rival in ("MAY", "BRENDAN"):
    for place, stage in RIVAL_STAGE_FOR_ID.items():
        for suffix, family in STARTER_FOR_SUFFIX.items():
            tid = f"TRAINER_{rival}_{place}_{suffix}"
            team = [m.copy() for m in RIVAL_CORE[stage]] + [starter_mon(family, stage)]
            BOSSES[tid] = (AI_TOP if stage in ("R119", "LILYCOVE") else AI_BOSS, team)

# ---------------------------------------------------------------------------
# Derived rematches: same team, flat level offsets.
# ---------------------------------------------------------------------------

DERIVED = {}
for leader in ("ROXANNE", "BRAWLY", "WATTSON", "FLANNERY", "NORMAN", "WINONA",
               "TATE_AND_LIZA", "JUAN"):
    for i, offset in ((2, 6), (3, 12), (4, 18), (5, 24)):
        DERIVED[f"TRAINER_{leader}_{i}"] = (f"TRAINER_{leader}_1", offset)
for i, offset in ((2, 4), (3, 8), (4, 12), (5, 16)):
    DERIVED[f"TRAINER_WALLY_VR_{i}"] = ("TRAINER_WALLY_VR_1", offset)


def all_teams():
    teams = dict(BOSSES)
    for tid, (base, offset) in DERIVED.items():
        ai, mons = teams[base]
        bumped = []
        for m in mons:
            m2 = m.copy()
            m2["level"] = min(255, m["level"] + offset)
            bumped.append(m2)
        teams[tid] = (ai, bumped)
    return teams


def render_mon(m):
    lines = [f"{m['species']} @ {m['item']}",
             f"Level: {m['level']}",
             IVS,
             m["evs"],
             f"Nature: {m['nature']}"]
    if m["ability"]:
        lines.append(f"Ability: {m['ability']}")
    lines.extend(f"- {mv}" for mv in m["moves"])
    return lines


def validate(teams):
    errors = []
    for tid, (ai, mons) in teams.items():
        if not 1 <= len(mons) <= 6:
            errors.append(f"{tid}: party size {len(mons)}")
        species = [m["species"] for m in mons]
        if len(set(species)) != len(species):
            errors.append(f"{tid}: duplicate species {species}")
        for m in mons:
            if not 5 <= m["level"] <= 255:
                errors.append(f"{tid}: {m['species']} level {m['level']}")
            if len(m["moves"]) != 4:
                errors.append(f"{tid}: {m['species']} has {len(m['moves'])} moves")
            if not m["item"]:
                errors.append(f"{tid}: {m['species']} missing item")
    return errors


def apply(text, teams):
    idx = re.search(r"(?m)^=== TRAINER_", text).start()
    preamble, body = text[:idx], text[idx:]
    sections = re.split(r"(?m)^(?==== TRAINER_)", body)
    out, replaced = [], set()
    for sec in sections:
        if not sec.strip():
            continue
        tid = sec.splitlines()[0].strip("= ").strip()
        if tid not in teams:
            out.append(sec.rstrip("\n"))
            continue
        lines = sec.rstrip("\n").splitlines()
        header = []
        for ln in lines:
            if ln.strip() == "":
                break
            if ln.startswith("AI:"):
                continue
            header.append(ln.rstrip())
        ai, mons = teams[tid]
        parts = header + [ai]
        for m in mons:
            parts.append("")
            parts.extend(render_mon(m))
        out.append("\n".join(parts))
        replaced.add(tid)
    return preamble + "\n\n".join(out) + "\n", replaced


def main():
    teams = all_teams()
    errors = validate(teams)
    if errors:
        for e in errors:
            print("ERROR:", e)
        sys.exit(1)

    text = PARTY_FILE.read_text()
    new_text, replaced = apply(text, teams)
    missing = sorted(set(teams) - replaced)
    if missing:
        for tid in missing:
            print(f"ERROR: no section found for {tid}")
        sys.exit(1)
    PARTY_FILE.write_text(new_text)
    print(f"authored teams:  {len(BOSSES)}")
    print(f"derived rematches: {len(DERIVED)}")
    print(f"sections replaced: {len(replaced)}")


if __name__ == "__main__":
    main()
