#!/usr/bin/env python3

"""
Usage: python3 generate_exp_tables.py [OUTPUT_FILE]

Generate the full experience table header (src/data/pokemon/experience_tables.h
format) covering levels 0-255 for all six Gen 3 growth rates: Medium Fast,
Erratic, Fluctuating, Medium Slow, Fast, and Slow.

Levels 1-100 use the exact piecewise Gen 3 formulas (matching the EXP_* macros
already defined in src/data/pokemon/experience_tables.h). The Erratic formula
(n^3 * (160-n) / 100) goes negative past level 160, so for ALL growth rates,
levels 101-255 are extended from the level-100 value using medium-fast deltas:

    exp(n) = exp(100) + (n^3 - 100^3)

This keeps every table strictly increasing (aside from the vanilla-accurate
0-at-level-1 case for Fluctuating/Medium Slow) and safely within u32 bounds.

If OUTPUT_FILE is given, the generated header is written there. Without it,
the script only runs the generator + validation and prints a summary; it does
not touch the repository's actual experience_tables.h.
"""

import pathlib
import sys

MIN_LEVEL = 1
MAX_LEVEL = 255
U32_MAX = 0xFFFFFFFF

GROWTH_RATES = [
    "Medium Fast",
    "Erratic",
    "Fluctuating",
    "Medium Slow",
    "Fast",
    "Slow",
]


def cube(n):
    return n * n * n


def square(n):
    return n * n


def exp_medium_fast(n):
    return cube(n)


def exp_fast(n):
    return (4 * cube(n)) // 5


def exp_slow(n):
    return (5 * cube(n)) // 4


def exp_medium_slow(n):
    return (6 * cube(n)) // 5 - (15 * square(n)) + (100 * n) - 140


def exp_erratic(n):
    if n <= 50:
        return (100 - n) * cube(n) // 50
    elif n <= 68:
        return (150 - n) * cube(n) // 100
    elif n <= 98:
        return ((1911 - 10 * n) // 3) * cube(n) // 500
    else:
        return (160 - n) * cube(n) // 100


def exp_fluctuating(n):
    if n <= 15:
        return ((n + 1) // 3 + 24) * cube(n) // 50
    elif n <= 36:
        return (n + 14) * cube(n) // 50
    else:
        return ((n // 2) + 32) * cube(n) // 50


# Order matches GROWTH_MEDIUM_FAST, GROWTH_ERRATIC, GROWTH_FLUCTUATING,
# GROWTH_MEDIUM_SLOW, GROWTH_FAST, GROWTH_SLOW in include/constants/pokemon.h
FORMULAS = [
    exp_medium_fast,
    exp_erratic,
    exp_fluctuating,
    exp_medium_slow,
    exp_fast,
    exp_slow,
]


def base_table(formula):
    """Levels 0-100. Level 0 is unused padding (always 0). Level 1 is
    hardcoded to 1 for every growth rate, matching vanilla ROM data (the raw
    formulas disagree with each other at n=1 -- e.g. Medium Slow goes
    negative, Fast evaluates to 0 -- but the real games store 1 uniformly).
    Levels 2-100 use the raw Gen 3 formula, clamped at 0 as a safety net."""
    table = [0] * (100 + 1)
    table[1] = 1
    for n in range(2, 101):
        table[n] = max(0, formula(n))
    return table


def extend_table(table):
    """Extend a 0-100 table out to MAX_LEVEL using medium-fast deltas from
    the level-100 value, per the CRITICAL note in the module docstring."""
    exp_100 = table[100]
    full = list(table) + [0] * (MAX_LEVEL - 100)
    for n in range(101, MAX_LEVEL + 1):
        full[n] = exp_100 + (cube(n) - cube(100))
    return full


def generate_tables():
    return [extend_table(base_table(formula)) for formula in FORMULAS]


def validate_tables(tables):
    """Assert strict monotonicity (non-decreasing 0->0 permitted only across
    levels 1-2 for Fluctuating/Medium Slow, matching vanilla where those two
    growth rates require 0 exp at level 1) and u32 bounds for every table."""
    for name, table in zip(GROWTH_RATES, tables):
        assert len(table) == MAX_LEVEL + 1, f"{name}: expected {MAX_LEVEL + 1} entries, got {len(table)}"
        assert table[0] == 0, f"{name}: level 0 must be 0, got {table[0]}"

        allow_plateau = name in ("Fluctuating", "Medium Slow")

        for n in range(1, MAX_LEVEL + 1):
            value = table[n]
            assert 0 <= value <= U32_MAX, f"{name}: level {n} value {value} out of u32 bounds"

            prev = table[n - 1]
            if allow_plateau and n <= 2:
                assert value >= prev, f"{name}: level {n} ({value}) < level {n - 1} ({prev})"
            else:
                assert value > prev, f"{name}: level {n} ({value}) is not strictly greater than level {n - 1} ({prev})"


def format_header(tables):
    lines = []
    lines.append("// Generated by tools/generate_exp_tables.py. Do not hand-edit.")
    lines.append("#define SQUARE(n) ((n) * (n))")
    lines.append("#define CUBE(n) ((n) * (n) * (n))")
    lines.append("")
    lines.append(f"const u32 gExperienceTables[][MAX_LEVEL + 1] =")
    lines.append("{")
    for name, table in zip(GROWTH_RATES, tables):
        lines.append(f"    {{ // {name}")
        for n, value in enumerate(table):
            lines.append(f"        {value}, // {n}")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def print_summary(tables):
    print(f"{'Growth Rate':<14} {'Lv100 EXP':>12} {'Lv255 EXP':>14}")
    for name, table in zip(GROWTH_RATES, tables):
        print(f"{name:<14} {table[100]:>12} {table[255]:>14}")


def main():
    tables = generate_tables()
    validate_tables(tables)
    print("Validation passed: all tables strictly increasing (vanilla plateau allowance"
          " honored for Fluctuating/Medium Slow at levels 1-2) and within u32 bounds.\n")
    print_summary(tables)

    if len(sys.argv) >= 2:
        output_file = pathlib.Path(sys.argv[1])
        output_file.write_text(format_header(tables))
        print(f"\nWrote generated header to {output_file}")


if __name__ == "__main__":
    main()
